### ISSUE TITLE
Why are tests related to $().focus() and keyup events on hidden elements & dialogs not working?

### ISSUE THREAD

**Issue by jrwdunham** [jrwdunham/dative#22]
Two distinct issues here but probably they're related.

1. tests can't recognize when an element is given focus. Probably because the element is rendered in a hidden fixture. See my (as yet unanswered) SO question at http://stackoverflow.com/questions/25755659/mocha-tests-on-focus-related-behaviors-backbone-coffeescript-app

2. tests can't trigger keyup (or keydown) events on a jQueryUI dialog.

**Comment by jrwdunham** [comment]
SO question answered. See http://stackoverflow.com/questions/25755659/mocha-tests-on-focus-related-behaviors-backbone-coffeescript-app

Basically, the tests I'm describing above are testing DOM behaviour and are therefore going outside of the purview of what a "unit test" canonically is. I just need to circumscribe what I'm testing: just test my functions/methods/classes' behaviours, don't test the DOM. I'm closing this.

**Comment by cesine** [comment]
@jrwdunham  if you like the answer on SO you should accept it.. 

i think hes avoiding your question because you wrote `unit` test instead of `e2e test` or something larger than a unit test. he assumes you're using selenium for functionality or `acceptance` testing... youre not. youre trying to use mocha no? 

eitherway, you if you like his answer,  you should accept it so he gets his SO cred :)
